merchex/urls.py

from django.contrib import admin
from django.urls import path
from django.core.mail import send_mail
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('about-us/', views.about, name='about-us'),
    path('contact-us/', views.contact, name='contact-us'),
    path('email/', views.send_mail, name='email-sent'),
    path('listings/', views.listings,name='list'),
    path("bands/<int:band_id>/",views.band_detail, name='band-detail'),
    path('listings/<int:id>', views.listing_detail, name = 'list-detail'),
    path('bands/<int:id>/change', views.band_update, name = 'band-update'),
    path('bands/add/', views.band_create, name = 'band-create'),
    path('bands/<int:id>/delete', views.band_delete, name = 'band-delete'),
]

listings/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator

# Create your models here.
class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        BIKUTSI = 'B'
        POP = 'PP'

    name = models.fields.CharField(max_length=100)
    genre= models.fields.CharField(choices= Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=50)
    year_formed = models.fields.IntegerField( validators=[MinValueValidator(1990),MaxValueValidator(2025)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    # like_new = models.fields.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'

class Listing(models.Model):
    class Types(models.TextChoices):
        Record = 'Re'
        Clothing = 'Cl'
        Posters = 'Po'
        Miscellaneous = 'Mi'
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=200)
    sold = models.fields.BooleanField(default=True)
    year = models.fields.IntegerField(validators=[MinValueValidator(1990),MaxValueValidator(2025)])
    type = models.fields.CharField(choices= Types.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete= models.SET_NULL)

    def __str__(self):
        return f'{self.title}'



listings/forms.py
from django.forms import fields
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django import forms
from listings.models import Band

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length="1000")

class BandForm(forms.ModelForm):
   class Meta:
     model = Band
     exclude = ('active', 'official_homepage')

listings/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.mail import send_mail
from listings.models import Band, Listing
from listings.forms import BandForm, ContactUsForm



def band_delete(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        band.delete()
        return redirect('band-list')

    return render(request,'listings/band_delete.html',{'band': band})
           


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            
            return redirect('band-detail', band.id)

    else:
        form = BandForm()

    return render(request,'listings/band_create.html',{'form': form})



def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,'listings/band_update.html',{'form': form})



def band_list(request):
    bands = Band.objects.all()
    print(request.path)
    return render(request, 'listings/band_list.html', {'bands': bands})



def about(request):
    print(request.path)
    return render(request,'listings/about.html')



def email_send(request):
    return render(request,'listings/email_sent.html')



def contact(request):
    print(request.path)
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject = f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx contact Us form',
                message = form.cleaned_data['message'],
                from_email = form.cleaned_data['email'],
                recipient_list = ['admin@merchex.xyz'],
            )    
        # return redirect('email-sent')    
    else:
        form = ContactUsForm()

    return render(request,'listings/contact.html', {'form' : form})


def listings(request):
    print(request.path)
    titles = Listing.objects.all()
    return render(request,'listings/listings.html', {'titles':titles})

def band_detail(request, band_id):
    band = Band.objects.get( id = band_id)
    return render(request, 'listings/band_detail.html',{'band' : band})

def listing_detail(request, id):
    list = Listing.objects.get( id = id)
    return render(request,'listings/listing_detail.html',{'list' : list})


listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

    <div class="h2">
        <h1 class="h1">A propos de NOUS</h1>
    </div>    
    <p style="text-align: center;">Nous somme une entreprise qui fait dans le develloppement des applications web </p>
{% endblock %}

listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouveau groupe</h1>

<form action="" method="post" >
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content  %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
    </form>
{% endblock  %}

listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
        <h2>{{ band.name }}</h2>
        <ul>
            <li>Genre : {{ band.get_genre_display }}</li>
            <li>Année de formation : {{ band.year_formed }}</li>
            <li>Actif : {{ band.active | yesno }}</li>
            {% if  band.official_homepage %}
                <li>
                    <a href="{{band.official_homepage}}">{{ band.official_homepage }}</a>
                </li>
            {% endif %}
        </ul>
        <p>{{ band.biography }}</p>
        <h3><a href="{% url 'band-list' %}">BACK</a></h3>
   
    
{% endblock %}

listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}
    <div class="h2">
        <h1 class="h1">Hello Django!</h1>
    </div>    

    <div class="btn-create1">
        <a href="{% url 'band-create' %}" class="btn-create">Créer un nouveau groupe</a>
    </div>

    <div class="list1">
            <div class="ennonce">
                <h2 >Mes groupes préférés sont </h2>
            </div>

            <div class="list">
                <ul>
                    {% for band in bands%}
                        <div class="listInt">
                            <li><a href="{% url 'band-detail' band.id %}">{{band.name}}</a><li>
                            <div class="listAct">    
                                <a class="btn-act btn-mod" href="{% url 'band-update' band.id %}">Modifier</a>
                                <a class="btn-act btn-sup" href="{% url 'band-delete' band.id %}">Supprimer</a>
                            </div>        
                        </div>     
                        <hr style="margin-right: 30px;">   
                    {% endfor %}
                </ul>
            </div>
    <div>            
{% endblock %}

listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content  %}
    <h1>Mise à jour du groupe</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>
{% endblock  %}

listings/templates/listings/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}">
    
</head>
<body>
    <nav class="nav">
        <h2 class="merchex">Merchex</h2>
        <a href="{% url 'band-list' %}" class="lien {% if request.path == '/bands/' %} border-b-2  lienActu {% endif %} href="{% url 'band-list' %}" ">Groups</a>
        <a href="{% url 'list' %}" class="lien {% if request.path == '/listings/' %} border-b-2  lienActu {% endif %} href="{% url 'list' %}" ">Listing</a>
        <a href="{% url 'about-us' %}" class="lien {% if request.path == '/about-us/' %} border-b-2  lienActu {% endif %} href="{% url 'about-us' %}" ">About us</a>
        <a href="{% url 'contact-us' %}" class="lien {% if request.path == '/contact-us/' %} border-b-2  lienActu {% endif %} href="{% url 'contact-us' %}" ">Contact Us</a>
    </nav>
    <hr class="hr1">
    {% block content %}

    {% endblock %}
</body>
</html>

listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}
    <div class="h2">
        <h1 class="h1">Contactez Nous</h1>
    </div> 
    <div class="ennonce">   
        <h2>Nous somme la pour vous aider</h2>
    </div>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="formList">
            {{form.as_p }}
            <input type="submit" value="Soumettre" class="btnsoum">
        </div>    
    </form>
{% endblock %}

listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Email</h1>


{% endblock  %}

listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Mon albums  </h1>
    <p>
        <h3>{{list.title}}</h3>
        <ul>
            <li>Année : {{list.year}}</li>
            <li>Type : {{list.get_type_display}}</li>
            <li>En solde : {{list.sold | yesno}}</li>
            <li>Groupes <a href="">{{list.band}}</a></li>
        </ul>
        <p>{{list.description}}</p>
    </p>

    <p>{{ band.biography }}</p>

    {% comment %} <a href="{% url 'band-update' band.id %}">Modifier ce groupe</a> {% endcomment %}
  
    <a href="{% url 'band-list' %}">Retourner à la liste des groupes</a>
{% endblock %}

listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}
    <div class="h2">
        <h1 class="h1">Voila mes albums  </h1>
    </div>

    <div class="list">
        <p>
            <ul>
                {% for tit in titles %}
                <div class="listInt">
                        <li><a href="{% url 'list-detail' tit.id %}">{{tit.title}}</a></li>
                </div>
                <hr style="margin-right: 30px;"> 
                {% endfor %}
            </ul>
        </p>
    </div>    
{% endblock %}